sudo: required
cache: apt

addons:
  apt:
    sources: &apt_sources
      - sourceline: 'ppa:adrozdoff/cmake' # cmake 3 for trusty
    packages: &default_packages
      - cmake
      - g++-4.9

before_install:
  - sudo apt install ninja

install:
  - .travis/install-lean.sh
