sudo: required
cache: 
  apt:
  directories:
  - lean

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:adrozdoff/cmake' # cmake 3 for trusty
    packages: &default_packages
      - cmake
      - g++-6

install:
  - .travis/install-lean.sh

script:
  - cd galois/
  - ../lean/bin/leanpkg configure
  - ../lean/bin/lean --make

