sudo: required
cache: apt

addons:
  apt:
    sources: &apt_sources
      - sourceline: 'ppa:adrozdoff/cmake' # cmake 3 for trusty
    packages: &default_packages
      - cmake
      - g++-6

install:
  - .travis/install-lean.sh
